# Generated by Django 6.0.2 on 2026-02-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('en_seguimiento', 'En seguimiento'), ('contactado', 'Contactado'), ('en_negociacion', 'En negociación'), ('cerrado', 'Cerrado')], default='nuevo', max_length=20),
        ),
    ]
